### ISSUE TITLE
what about i18n and multiple calendar?

### ISSUE THREAD

**Issue by mhf-ir** [bevry/daet#1]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

see aslo
https://mhf-ir.github.io/i18nplease/

**Comment by balupton** [comment]
It already uses this:

https://github.com/bevry/daet/blob/9264510802e367e6221cadd702abdfd24b3ace27/source/index.ts#L261-L264

So I'm not sure what is being asked here.

You can also override the relative time formats by extending the class and overriding the `tiers` property with your own custom relative time tiers.
